Parent
WildCodeSchool-2023-09/remfr-php-p3-babyplace pull request #41
Opened 2024-01-29 09:15 UTC by Carcali

- Moyens de paiement
- Réserver un créneau (modal)
- Stylisation du CRUD "Ajouter un enfant"
- Remise en place de la progress bar et du header au niveau du register, uniquement dans l'inscription de la crèche

2024-01-29 09:17 UTC, Williamlh33 approved these changes

2024-01-29 18:26 UTC, vincentr-wcs requested changes

2024-01-29 18:26 UTC, vincentr-wcs commented on docker-compose.prod.yml
> +      DATABASE_URL: mysql://lily:poupou@127.0.0.1:3306/$babyplace?serverVersion=8&charset=utf8mb4
Pourquoi vous avez changé ses fichiers ? Normalement faut les laisser tel quel

2024-01-29 18:26 UTC, vincentr-wcs commented on docker-compose.yml
> +      DATABASE_URL: mysql://lily:poupou@database:3306/babyplace?serverVersion=8&charset=utf8mb4
idemi sur ce fichier

2024-02-05 14:26 UTC, elisechldn approved these changes

2024-02-06 08:23 UTC, Yazzz28 approved these changes

2024-02-06 08:44 UTC, merged